### PR TITLE
Revert "Add test for variable interpolation in HTML"

### PR DESCRIPTION
**Pull request by sg1303**
Fix broken travis build.

### CODE REVIEW

**Comment by sg1303** [comment]
Reverted addition of test case that tried to add an interpolated string inside of an html comment, but it's evaluated as plaintext like this says:

> Jade does not have any special syntax for conditional comments. If your line begins with `<` then it is > treated as plain text.

**Comment by TimothyGu** [comment]
A test case this there for a reason. The code should be fixed if the test fails.

**Comment by sg1303** [comment]
I don't understand... sounds like you are proposing a feature be added? In my mind this is currently working as designed.

**Comment by ForbesLindesay** [comment]
We allow interpolation in plain text. We already have `//` for true comments.  HTML comments are intended for things like knockout conditionals, where you would want interpolation to work.

**Comment by sg1303** [comment]
That makes sense. Thanks for clarifying.

**Pull request closed without merging**
